
//Login y registro de usuario.
export const REGISTRANDO_USUARIO = 'REGISTRANDO_USUARIO';
export const USUARIO_REGISTRADO_EXITO = 'USUARIO_REGISTRADO_EXITO';
export const USUARIO_REGISTRADO_ERROR = 'USUARIO_REGISTRADO_ERROR';

export const USERDATA = 'USERDATA';
export const CLEANERROR = 'CLEANERROR';
